<?php
return [
	'manager/admin' => '财务-用户－查看列表',
    'manager/create' => '财务-用户－创建',
    'manager/delete' => '财务-用户－删除',
    'manager/update' => '财务-用户修改',
    'manager/reset-password'=>'财务-用户－修改密码',

    'auth/permlist'=>['财务-用户－权限列表','权限'],
    'auth/rolelist'=>['财务-用户－角色列表','权限'],
    'auth/flushperms'=>['财务-用户－更新权限','权限'],
    'auth/assign'=>['财务-用户－分配权限','权限'],
    'auth/assignment'=>['财务-用户－分配角色','权限'],
    'auth/update'=>['财务-用户－修改权限','权限'],
    'auth/delete'=>['财务-用户－删除权限','权限'],

    'refund/list'=>['财务-退款管理-退款列表','退款管理'],
    'refund/do'=>['财务-退款管理-退款','退款管理'],
    'refund/batch'=>['财务-退款管理-批量退款','退款管理'],
    'refund/reject'=>['财务-退款管理-拒绝退款','退款管理'],

    'settlement/list'=>['财务-结算管理-首页列表','结算管理'],
    'settlement/detail'=>['财务-结算管理-买手详情','结算管理'],
    'settlement/ignore'=>['财务-结算管理-忽略单笔订单','结算管理'],
    'settlement/recover'=>['财务-结算管理-恢复单笔订单','结算管理'],
    'settlement/adjust'=>['财务-结算管理-调整单笔订单','结算管理'],
    'settlement/singlepay'=>['财务-结算管理-结算单笔订单','结算管理'],
    'settlement/batchignore'=>['财务-结算管理-批量忽略订单','结算管理'],
    'settlement/batchadjust'=>['财务-结算管理-批量调整订单','结算管理'],
    'settlement/batchpay'=>['财务-结算管理-批量结算订单','结算管理'],
    'settlement/paytobuyer'=>['财务-结算管理-单个买手结算','结算管理'],
    'settlement/buyers'=>['财务-结算管理-批量买手结算待结算列表','结算管理'],
    'settlement/clear'=>['财务-结算管理-最终结算','结算管理'],
    'settlement/history'=>['财务-结算管理-历史结算列表','结算管理'],
    'settlement/historydetail'=>['财务-结算管理-历史结算详情','结算管理'],
    'settlement/ignorebuyer'=>['财务-结算管理-忽略买手','结算管理'],
    'settlement/ignore-batch-orders'=>['财务-结算管理-忽略买手订单','结算管理'],
    'settlement/notelist'=>['财务-结算管理-订单备注','结算管理'],
    'settlement/export'=>['财务-结算管理-导出结算清单','结算管理'],
];